// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDat8GwJUWdXjdUTfNx0t7MNDc1e3rflvE',
    appId: '1:183099438316:web:ee70f437671602698d61c9',
    messagingSenderId: '183099438316',
    projectId: 'kems-app-820d3',
    authDomain: 'kems-app-820d3.firebaseapp.com',
    storageBucket: 'kems-app-820d3.firebasestorage.app',
    measurementId: 'G-7Q6CVJFH42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXo9OnYbNArlqbEw-mplx4E3iFZPfqwHE',
    appId: '1:183099438316:android:0bb7e69ecf8537c98d61c9',
    messagingSenderId: '183099438316',
    projectId: 'kems-app-820d3',
    storageBucket: 'kems-app-820d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFAWpJudK2_stW_RkEbepWpR_xoDN-gy0',
    appId: '1:183099438316:ios:a10b7f3ba25b3dd58d61c9',
    messagingSenderId: '183099438316',
    projectId: 'kems-app-820d3',
    storageBucket: 'kems-app-820d3.firebasestorage.app',
    iosBundleId: 'com.kdse.kemsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFAWpJudK2_stW_RkEbepWpR_xoDN-gy0',
    appId: '1:183099438316:ios:a10b7f3ba25b3dd58d61c9',
    messagingSenderId: '183099438316',
    projectId: 'kems-app-820d3',
    storageBucket: 'kems-app-820d3.firebasestorage.app',
    iosBundleId: 'com.kdse.kemsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDat8GwJUWdXjdUTfNx0t7MNDc1e3rflvE',
    appId: '1:183099438316:web:fa3697b28b2e5b2b8d61c9',
    messagingSenderId: '183099438316',
    projectId: 'kems-app-820d3',
    authDomain: 'kems-app-820d3.firebaseapp.com',
    storageBucket: 'kems-app-820d3.firebasestorage.app',
    measurementId: 'G-TJE40VNL4L',
  );
}
